-- Example INSERT format (PostgreSQL-style types shown; SQLite uses INTEGER/REAL/TEXT).
-- Full production-like dataset (120 events / 50 users / 250 rows) is generated by
-- TicketingDataSeeder.seed() — not shipped as raw SQL due to size.

INSERT INTO users (full_name, email, phone) VALUES
('Amélie Tremblay', 'amelie.tremblay0@mail.example', '(514) 200-1010'),
('Marcus Nguyen', 'marcus.nguyen7@mail.example', '(524) 217-1027'),
('Priya Roy', 'priya.roy14@mail.example', '(534) 234-1044');

INSERT INTO events (title, description, category, organizer, venue, city, date, start_time, end_time,
    capacity, registered_count, price, is_free, status, image_name, contact_email) VALUES
('Osheaga Afterdark: Analog Dreams', 'Join us for Osheaga Afterdark...', 'Concert', 'Evenko Live',
 'MTelus', 'Montreal', '2026-04-04', '17:07', '20:11', 80, 0, 89.0, 0, 'upcoming', 'event_concert_001.webp',
 'tickets.concert0@venue.example'),
('Alouettes Preseason: Red & Blue Scrimmage', 'Join us for Alouettes...', 'Sports', 'Montreal Sports Group',
 'Olympic Stadium', 'Montreal', '2026-04-07', '18:14', '21:22', 10, 10, 35.0, 0, 'full', 'event_sports_002.webp',
 'tickets.sports1@venue.example');

INSERT INTO registrations (user_id, event_id, registration_date, ticket_type, payment_status) VALUES
(1, 2, '2026-04-07 10:00:00', 'standard', 'paid'),
(2, 2, '2026-04-07 10:03:00', 'vip', 'paid');
